[package]
name = "sphere_view"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
rand = "0.9.2"

[profile.release]
opt-level = "z" # Or "z" for even smaller size
lto = "fat"    # Or "fat" for more aggressive LTO
codegen-units = 1
strip = "debuginfo"
